# Generated by Django 3.2.12 on 2022-04-04 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField(blank=True, null=True)),
                ('job_types', models.CharField(choices=[('Part Time', 'Part Time'), ('Full Time', 'Full Time'), ('Other', 'Other')], max_length=9)),
                ('job_responsibilities', models.CharField(choices=[('Develop', 'Develop'), ('Support', 'Support'), ('Maintenance', 'Maintenance'), ('Quality Assurance', 'Quality Assurance'), ('DevOps', 'DevOps')], max_length=17)),
                ('date_of_publish', models.DateTimeField(auto_now_add=True)),
                ('monthly_salary', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
