# Generated by Django 3.2.12 on 2022-04-03 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import services_products.products.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('screenshot', models.ImageField(blank=True, default='default-image.jpeg', null=True, upload_to='items/', validators=[services_products.products.validators.MaxFileSizeInMbValidator(5)])),
                ('type', models.CharField(choices=[('Template', 'Template'), ('Plugin', 'Plugin'), ('Module', 'Module'), ('Other', 'Other')], max_length=8)),
                ('date_of_release', models.DateTimeField(auto_now_add=True)),
                ('price', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
